# app.yaml

runtime: python39
env: standard
entrypoint: gunicorn -b :$PORT afl_tipster.wsgi:application

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto

runtime_config:
  python_version: 3