# Generated by Django 4.2.1 on 2023-06-02 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AFLFixture',
            fields=[
                ('id', models.CharField(default='', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('timestr', models.CharField(default='', max_length=100, null=True)),
                ('winner', models.CharField(default='', max_length=100, null=True)),
                ('unixtime', models.BigIntegerField()),
                ('ateam', models.CharField(default='', max_length=100, null=True)),
                ('complete', models.IntegerField(default=0)),
                ('roundname', models.CharField(default='', max_length=100, null=True)),
                ('hbehind', models.IntegerField(default=0)),
                ('is_final', models.CharField(default=0, max_length=100, null=True)),
                ('hgoals', models.IntegerField(default=0)),
                ('localtime', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(default='', max_length=100, null=True)),
                ('ascore', models.IntegerField(default=0)),
                ('is_grand_final', models.CharField(default=0, max_length=100, null=True)),
                ('winnerteamid', models.IntegerField(default=0)),
                ('ateamid', models.IntegerField(default=0)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('abehinds', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('hscore', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('round', models.IntegerField(default=0)),
                ('tz', models.CharField(default=0, max_length=100, null=True)),
                ('hteam', models.CharField(default=0, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AFLTeams',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=100, null=True)),
                ('logo', models.CharField(default='', max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tip_summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='tippings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100, null=True)),
                ('last_name', models.CharField(default='', max_length=100, null=True)),
                ('email', models.CharField(default='', max_length=100, null=True)),
                ('margin', models.IntegerField(default=0)),
                ('margin_diff', models.IntegerField(default=0)),
                ('tips', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('fixture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afl_fixture', to='tipping.aflfixture')),
            ],
        ),
        migrations.AddField(
            model_name='aflfixture',
            name='agoals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='tipping.aflteams'),
        ),
        migrations.AddField(
            model_name='aflfixture',
            name='hteamid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='tipping.aflteams'),
        ),
    ]
