# Generated by Django 4.2.1 on 2023-06-02 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipping', '0002_alter_aflfixture_agoals_alter_aflfixture_ateamid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aflfixture',
            name='ateamid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='tipping.aflteams'),
        ),
        migrations.AlterField(
            model_name='aflfixture',
            name='hteamid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='tipping.aflteams'),
        ),
        migrations.AlterField(
            model_name='aflfixture',
            name='winnerteamid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winning_team', to='tipping.aflteams'),
        ),
    ]
