# Generated by Django 4.2.1 on 2023-06-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipping', '0005_alter_aflteams_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aflfixture',
            name='id',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False),
        ),
    ]
