# Generated by Django 4.2.1 on 2023-06-02 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipping', '0006_alter_aflfixture_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tippings',
            name='picks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picked_team', to='tipping.aflteams'),
        ),
    ]
