# Generated by Django 4.2.1 on 2023-06-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipping', '0009_alter_tippings_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tippings',
            name='fixture_id',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tippings',
            name='picks',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
