# Generated by Django 4.2.1 on 2023-06-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipping', '0010_alter_tippings_fixture_id_alter_tippings_picks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tippings',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
