# Generated by Django 4.2.1 on 2023-06-03 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipping', '0012_tippings_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='tippings',
            name='status',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
