# Generated by Django 4.2.1 on 2023-06-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipping', '0013_tippings_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tippings',
            name='round',
            field=models.IntegerField(default=0),
        ),
    ]
