# Generated by Django 4.2.1 on 2023-06-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipping', '0014_tippings_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='tippings',
            name='has_margin',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
