# Generated by Django 4.2.1 on 2023-06-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipping', '0015_tippings_has_margin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AFLLadder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField(default=0)),
                ('clud', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('played', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('lose', models.IntegerField(default=0)),
                ('draw', models.IntegerField(default=0)),
                ('point', models.IntegerField(default=0)),
            ],
        ),
    ]
