# Generated by Django 4.2.1 on 2023-06-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipping', '0018_aflladder_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aflladder',
            name='id',
        ),
        migrations.AlterField(
            model_name='aflladder',
            name='pos',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
