# Generated by Django 4.2.1 on 2023-06-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipping', '0019_remove_aflladder_id_alter_aflladder_pos'),
    ]

    operations = [
        migrations.CreateModel(
            name='tip_ladder',
            fields=[
                ('email', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('full_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('total_tips', models.IntegerField(blank=True, default=0, null=True)),
                ('total_margin', models.IntegerField(blank=True, default=0, null=True)),
                ('avg_per_round', models.FloatField(blank=True, default=0, null=True)),
                ('rank', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='tip_summary',
        ),
    ]
