# Generated by Django 4.2.1 on 2023-06-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipping', '0020_tip_ladder_delete_tip_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip_ladder',
            name='last_round_margin',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tip_ladder',
            name='last_round_tips',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
