# Generated by Django 4.2.1 on 2023-06-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipping', '0021_tip_ladder_last_round_margin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip_ladder',
            name='rounds_tipped',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
