# Generated by Django 4.2.1 on 2023-06-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipping', '0024_alter_aflfixture_agoals_alter_aflfixture_ascore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tippings',
            name='auto',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
