# Generated by Django 4.2.1 on 2023-06-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipping', '0025_tippings_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tippings',
            name='disabled',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
